# Generated by Django 4.1.1 on 2022-10-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('code', models.CharField(max_length=128)),
                ('cluster', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('campus', models.CharField(max_length=128)),
                ('time', models.CharField(max_length=128)),
                ('intensity', models.IntegerField()),
                ('classroom', models.CharField(max_length=128)),
                ('day', models.CharField(max_length=16)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('document', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('secondname', models.CharField(blank=True, max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('secondsurname', models.CharField(max_length=64)),
                ('email', models.EmailField(blank=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('address', models.CharField(blank=True, max_length=64)),
                ('rank', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.IntegerField()),
                ('class_date', models.DateField()),
                ('impact', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.teacher')),
            ],
        ),
    ]
