# Generated by Django 4.1.1 on 2022-10-09 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
